language: python
python:
#  - "2.7"
  - "3.5"
install:
  - git clone --branch=develop https://github.com/confirm/ansibleci.git pstauffer/ansibleci
script:
  - python pstauffer/ansibleci/test.py

#install:
#  - pip install ansibleci PyYAML
#script:
#  - python testing/test.py
