language: python
python:
#  - "2.7"
  - "3.5"
install:
  - git clone --branch=develop https://github.com/confirm/ansibleci.git testing/ansibleci
  - pip install PyYAML
  - cp testing/settings.py testing/ansibleci/settings.py
script:
  - python testing/ansibleci/test.py

#install:
#  - pip install ansibleci PyYAML
#script:
#  - python testing/test.py
