language: python
python:
 # - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
install:
  - pip install ansibleci PyYAML ansible
script:
  - python test/test.py
  - ansible-playbook --syntax-check test/playbook.yml
  - ansible-playbook --sudo -v --diff test/playbook.yml
  - >
    ansible-playbook --sudo test/playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
