language: python
python:
#  - "2.7"
  - "3.5"
install:
  - git clone --branch=develop https://github.com/confirm/ansibleci.git pstauffer/ansibleci
  - pip install PyYAML
  - ls -l
script:
  - ls -l
#  - python ../../ansibleci/test.py

#install:
#  - pip install ansibleci PyYAML
#script:
#  - python testing/test.py
